development:
  adapter: postgresql
  encoding: unicode
  database: user_development
  pool: 5
  username: Manoj
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: user_test
  pool: 5
  username: Manoj
  password:


